# Generated by Django 4.1.3 on 2023-06-15 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryearnings',
            options={'verbose_name': 'Categoria dos ganhos', 'verbose_name_plural': 'Categorias dos ganhos'},
        ),
        migrations.AlterModelOptions(
            name='categoryexpenses',
            options={'verbose_name': 'Categoria das despesas', 'verbose_name_plural': 'Categorias das despesas'},
        ),
        migrations.AlterModelOptions(
            name='earnings',
            options={'verbose_name': 'Ganho', 'verbose_name_plural': 'Ganhos'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.RemoveField(
            model_name='earnings',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='observation',
        ),
        migrations.AddField(
            model_name='earnings',
            name='recurrence',
            field=models.BooleanField(default=False, verbose_name='Recorrência'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='recurrence',
            field=models.BooleanField(default=False, verbose_name='Recorrência'),
        ),
        migrations.AlterField(
            model_name='categoryearnings',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='categoryexpenses',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeapp.categoryearnings', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='earnings',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=50000000000000, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeapp.categoryexpenses', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=50000000000000, verbose_name='Valor'),
        ),
    ]
