# Generated by Django 4.1.3 on 2023-06-29 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueID',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='earnings',
            name='unique_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeapp.uniqueid', verbose_name='ID único'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='unique_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeapp.uniqueid', verbose_name='ID único'),
        ),
    ]
