# Generated by Django 4.1.3 on 2023-06-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_uniqueid_alter_earnings_unique_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earnings',
            old_name='unique_id',
            new_name='unique',
        ),
        migrations.RenameField(
            model_name='expenses',
            old_name='unique_id',
            new_name='unique',
        ),
    ]
