# Generated by Django 4.1.3 on 2023-06-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0002_alter_categoryearnings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='recurrence',
            field=models.BooleanField(default=False, verbose_name='Despesa recorrente'),
        ),
    ]
