# Generated by Django 4.1.3 on 2023-06-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeapp', '0003_alter_expenses_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='earnings',
            name='type',
            field=models.CharField(default='earning', max_length=15, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='type',
            field=models.CharField(default='expense', max_length=100, verbose_name='Tipo'),
        ),
    ]
